# Generated by Django 4.2.7 on 2024-09-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_two_factor',
            field=models.BooleanField(default=False),
        ),
    ]
