# Generated by Django 4.2.7 on 2024-09-05 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_has_two_factor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
    ]
