# Generated by Django 4.2.7 on 2024-04-25 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_products_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('id',), 'verbose_name': 'Карегорию', 'verbose_name_plural': 'Категории'},
        ),
    ]
